name: TestNoDocker
on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: build Linux
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Setup Env
      run: |
        #set -x
        #set -v
        echo "pwd: $(pwd)"
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
        THIS_REPO_DIR=${GITHUB_WORKSPACE}/${GITHUB_REPOSITORY##*/}
        TOOLS_DIR=${THIS_REPO_DIR}/.github/tools

        for i in THIS_REPO_DIR TOOLS_DIR; do
          eval "r=\"\$$i\""
          echo "$i=$r" >> $GITHUB_ENV
        done
    - name: Checkout
      uses: actions/checkout@v4
    - name: Check AppImage exist
      run: |
        set -x
        set -v
        ls -la "$TOOLS_DIR/appimagetool-x86_64.AppImage" 
        #find / -iname "*.AppImage" 2>/dev/null

    - name: Mod AppImage to use chrome-sandbox of local os
      if: ${{ success() }}
      run: |
        set -x
        set -v
        mkdir t
        cd t
        mkdir squashfs-root
        echo "Test" >squashfs-root/Test.txt
        TOOL="$TOOLS_DIR/appimagetool-x86_64_2019-05-01.AppImage"
        ls -la ${TOOL}
        ARCH=x86_64 "{TOOL}" squashfs-root
        rm -r squashfs-root/
        rm "${EXE}"
        mv *.AppImage ../
        cd ..
        rm -r t


